development:
  title  : 
  uri    : 
  proxy  : 
  map_key: 
  mail_domain : 
  
test:
  title  : 
  uri    : 
  proxy  :
  map_key: 
  mail_domain : 

production:
  title  : Joruri Gw
  uri    : http://127.0.0.1/
  proxy  : 
  map_key: 
  mail_domain : 127.0.0.1
