development:
  secret_key_base: 'joruri_gw_secret_key_base_development'
test:
  secret_key_base: 'joruri_gw_secret_key_base_test'
production:
  secret_key_base: 'joruri_gw_secret_key_base_production'
