defaults: &defaults
  schedule_class_types:
    _belong: 所属
    _prop_genre_extras: 一般施設
  schedule_system_settings:
    week_view_piecehead_format: "%Y年%m月%d日（%_wd）"
    week_view_dayhead_format: "%m/%d(%_wd)"
    month_view_piecehead_format: "%Y年%m月"
    month_view_dayhead_format: "%_d"
    header_each: 5
    dayview_button_caption: 日表示
    weekview_button_caption: 週表示
    monthview_button_caption: 月表示
    custom_button_caption: カスタマイズ
    list_button_caption: 一覧
    restrict_regist_with_pm_by_operation_time: 1
    restrict_regist_with_pm_operation_time: 08:30-18:15
    restrict_regist_with_pm_by_reservation_time: 1
    restrict_regist_with_pm_reservation_time: 08:30-18:00
    restrict_regist_with_pm_by_rentcar_reservation_time: 1
    restrict_regist_with_pm_rentcar_reservation_time: 08:30-18:15
  schedule_props_settings:
    guardview_refresh: 300
    add_memo_send_to_confirm: 1
    add_memo_send_to_to_confirm: 4777-4782
    add_memo_send_to_announce: 1
  schedule_pref_admin:
    pref_admin_code: '000001_0'
  prop_extra_classes:
    meetingroom:
      pm: 管財課
    rentcar:
      pm: 管財課
  memo_mobile_settings:
    admin_email_from: admin@localhost.localdomain
    subject: "[連絡メモ]送信者："
  meeting_montor_settings:
    admin_email_from: admin@localhost.localdomain

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
